# Generated by Django 2.1.7 on 2019-06-11 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='distillery/uploads/%Y/%m/%d/')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralWhiskyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flora', models.IntegerField(default=0)),
                ('fruity', models.IntegerField(default=0)),
                ('sweetness', models.IntegerField(default=0)),
                ('creamy', models.IntegerField(default=0)),
                ('nutty', models.IntegerField(default=0)),
                ('malty', models.IntegerField(default=0)),
                ('spicy', models.IntegerField(default=0)),
                ('smoky', models.IntegerField(default=0)),
                ('peaty', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('publish_choice', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalWhiskyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flora', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('fruity', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('sweetness', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('creamy', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('nutty', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('malty', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('spicy', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('smoky', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('peaty', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Drinker', 'Drinker'), ('Lover', 'Lover'), ('Pro', 'Pro')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WhiskyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('year', models.IntegerField(default=0)),
                ('abv', models.IntegerField(default=0)),
                ('casktype', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='whisky/uploads/%Y/%m/%d/')),
                ('distillery', models.ManyToManyField(related_name='distillery', to='whiskydatabase.Distillery')),
            ],
        ),
        migrations.AddField(
            model_name='personalwhiskynote',
            name='whisky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_whisky', to='whiskydatabase.WhiskyInfo'),
        ),
        migrations.AddField(
            model_name='note',
            name='whisky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiskydatabase.WhiskyInfo'),
        ),
        migrations.AddField(
            model_name='generalwhiskynote',
            name='whisky',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gen_whisky', to='whiskydatabase.WhiskyInfo'),
        ),
    ]
