# Generated by Django 2.1.7 on 2019-06-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0003_auto_20190611_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillery',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='whiskyinfo',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='distillery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/distillery/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='whiskyinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/whisky/uploads/%Y/%m/%d/'),
        ),
    ]
