# Generated by Django 2.1.7 on 2019-06-13 02:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whiskydatabase', '0004_auto_20190613_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Comment',
        ),
    ]
