# Generated by Django 2.1.7 on 2019-06-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0006_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillery',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
