# Generated by Django 2.1.7 on 2019-06-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0011_auto_20190618_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalwhiskynote',
            old_name='sweetness',
            new_name='sweet',
        ),
        migrations.RenameField(
            model_name='personalwhiskynote',
            old_name='sweetness',
            new_name='sweet',
        ),
    ]
