# Generated by Django 2.1.7 on 2019-06-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0012_auto_20190618_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/country/uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='distillery',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distillery_country', to='whiskydatabase.Country'),
        ),
    ]
