# Generated by Django 2.1.7 on 2019-06-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0014_auto_20190620_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, upload_to='country/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='distillery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='distillery/uploads/%Y/%m/%d/'),
        ),
    ]
