# Generated by Django 2.1.7 on 2019-06-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0016_auto_20190621_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiskyinfo',
            name='abv',
            field=models.FloatField(default=0),
        ),
    ]
