# Generated by Django 2.1.9 on 2019-08-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0017_auto_20190621_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
