# Generated by Django 2.1.9 on 2019-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0018_auto_20190805_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskyinfo',
            name='general_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
