# Generated by Django 2.1.9 on 2019-08-15 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0019_whiskyinfo_general_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='region/uploads/%Y/%m/%d/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_country', to='whiskydatabase.Country')),
            ],
        ),
        migrations.AlterField(
            model_name='distillery',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distillery_region', to='whiskydatabase.Region'),
        ),
    ]
