# Generated by Django 2.2.4 on 2019-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0020_auto_20190815_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='creamy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='flora',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='fruity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='malty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='nutty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='peaty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='salty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='smoky',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='spicy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='sweet',
            field=models.IntegerField(default=0),
        ),
    ]
