# Generated by Django 2.2.4 on 2019-08-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0022_generalwhiskynote_total_notes_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distillery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
