# Generated by Django 2.2.4 on 2019-08-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0023_auto_20190827_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bar/uploads/%Y/%m/%d/')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_country', to='whiskydatabase.Country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_region', to='whiskydatabase.Region')),
            ],
        ),
    ]
