# Generated by Django 2.2.4 on 2019-08-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0025_auto_20190828_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillery',
            name='official_site',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='distillery',
            name='smws_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distillery',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
