# Generated by Django 2.2.4 on 2019-09-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0026_auto_20190830_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalwhiskynote',
            name='salty',
        ),
        migrations.RemoveField(
            model_name='generalwhiskynote',
            name='sweet',
        ),
        migrations.RemoveField(
            model_name='personalwhiskynote',
            name='salty',
        ),
        migrations.RemoveField(
            model_name='personalwhiskynote',
            name='sweet',
        ),
    ]
