# Generated by Django 2.2.4 on 2019-09-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0028_userprofile_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalwhiskynote',
            name='creamy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='generalwhiskynote',
            name='flora',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='generalwhiskynote',
            name='fruity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='generalwhiskynote',
            name='malty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='generalwhiskynote',
            name='nutty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='generalwhiskynote',
            name='peaty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='generalwhiskynote',
            name='smoky',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='generalwhiskynote',
            name='spicy',
            field=models.FloatField(default=0),
        ),
    ]
