# Generated by Django 2.2.4 on 2019-09-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0029_auto_20190914_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='creamy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='flora',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='fruity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='malty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='nutty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='peaty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='smoky',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalwhiskynote',
            name='spicy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
