# Generated by Django 2.2.4 on 2019-09-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0031_auto_20190920_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskyinfo',
            name='num_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='whiskyinfo',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
