# Generated by Django 2.2.4 on 2019-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskydatabase', '0032_auto_20190920_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bottle_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='distillery_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rate_num',
            field=models.IntegerField(default=0),
        ),
    ]
